### ISSUE TITLE
Whereis the mininit-syspart???

### ISSUE THREAD

**Issue by fanicy** [gcwnow/imager#2]
When I use create_system_image.sh:

There are have an error:

Checking presence of mininit-syspart...
missing program: mininit-syspart

BUT I CANT found THIS " mininit-syspart" in anywhere........

Where is it ??????????

Thank you!
-----------------------------
AND this command need the file modules.squashfs. There are no any information about it in readme.md.
FInally I found this file : in  https://github.com/gcwnow/linux/ 
after complied,run create_modules_fs.sh.

**Comment by pcercuei** [comment]
Hi,
You have to build mininit youself. The repository is here: https://github.com/OpenDingux/mininit
